on:
  pull_request:
    branches: [main]

name: Validate JSON

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./validator
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: validator/package-lock.json
      - run: npm ci
      - run: npm start
